# dentro do seu arquivo docker-compose.yml
services:
  db:
    image: postgres:13-alpine
    container_name: portfolio_db
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=portfolio_user
      - POSTGRES_PASSWORD=supersecretpassword
      - POSTGRES_DB=portfolio_db
    ports:
      - "5433:5432"
    restart: always